/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/edit` | `/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/feedback` | `/feedback`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/trips` | `/trips`; params?: Router.UnknownInputParams; } | { pathname: `${'/(support)'}` | `/`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}/edit` | `/edit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}/feedback` | `/feedback`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}/map` | `/map`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(customer)'}/trips` | `/trips`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(support)'}` | `/`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(customer)'}/edit${`?${string}` | `#${string}` | ''}` | `/edit${`?${string}` | `#${string}` | ''}` | `${'/(customer)'}/feedback${`?${string}` | `#${string}` | ''}` | `/feedback${`?${string}` | `#${string}` | ''}` | `${'/(customer)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(customer)'}/map${`?${string}` | `#${string}` | ''}` | `/map${`?${string}` | `#${string}` | ''}` | `${'/(customer)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(customer)'}/trips${`?${string}` | `#${string}` | ''}` | `/trips${`?${string}` | `#${string}` | ''}` | `${'/(support)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/edit` | `/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/feedback` | `/feedback`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/map` | `/map`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(customer)'}/trips` | `/trips`; params?: Router.UnknownInputParams; } | { pathname: `${'/(support)'}` | `/`; params?: Router.UnknownInputParams; };
    }
  }
}
